services:
  equity-aggregator:
    build:
      dockerfile: packages/equity-aggregator/Dockerfile
    container_name: equity-aggregator
    volumes:
      - ./data:/app/data

  streamlit-app:
    build:
      dockerfile: packages/streamlit-app/Dockerfile
    container_name: streamlit-app
    depends_on:
      equity-aggregator:
        condition: service_completed_successfully
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
