[project]
name = "database"
version = "0.1.0"
description = "database"
readme = "README.md"
requires-python = ">=3.12.5"
authors = [
    { name = "Gregory Kelleher", email = "gregory@gregorykelleher.com" }
]
dependencies = [
    "sqlalchemy>=2.0.37",
]

[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"
