name: publish-build-release
on:
  schedule:
    - cron: "0 01 * * *"   # daily 01:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: publish-build-release
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: env
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv (with cache)
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Sync environment
        run: uv sync --locked

      - name: Create .env file
        run: |
          printf '%b' "${{ secrets.EQUITY_AGGREGATOR_SECRETS }}" > .env
          chmod 600 .env
          test -s .env || { echo "::error ::empty .env"; exit 1; }

      - name: Clean previous data
        run: rm -rf data

      - name: Run Equity Aggregator
        env:
          UV_ENV_FILE: ".env"
        run: |
          mkdir -p data
          uv run equity-aggregator

      - name: Publish Latest Canonical Equities Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build-release
          name: latest-build-release
          make_latest: true
          fail_on_unmatched_files: true
          generate_release_notes: false
          files: |
            data/data_*_store.*
            data/logs/*.log