name: publish-build-release
on:
  schedule:
    - cron: "0 01 * * *"   # daily 01:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: publish-build-release
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - uses: actions/checkout@v4

      - name: Build Equity Aggregator Docker Image
        run: docker build -f Dockerfile -t equity-aggregator:latest .

      - name: Create .env file
        run: |
          printf '%b' "${{ secrets.EQUITY_AGGREGATOR_SECRETS }}" > .env
          chmod 600 .env
          test -s .env || { echo "::error ::empty .env"; exit 1; }

      - name: Run Equity Aggregator
        run: |
          mkdir -p dist
          docker run --rm \
            -v "$PWD/.env:/app/.env:ro" \
            -v "$PWD/dist:/app/data" \
            equity-aggregator:latest

      - name: Publish Latest Canonical Equities Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build-release
          name: latest-build-release
          make_latest: true
          fail_on_unmatched_files: true
          generate_release_notes: false
          files: |
            dist/data_store/data_store.db
            dist/logs/*.log